### ISSUE TITLE
icingaweb2::module::module_dir parameter default value should probably not be undef

### ISSUE THREAD

**Issue by rgevaert** [Icinga/puppet-icingaweb2#147]
running the following code
```
  icingaweb2::module { 'doc':
    install_method => 'none',
  }
```
produces the following error:
```
Error: Parameter target failed on File[/etc/icingaweb2/enabledModules/doc]: Invalid value "". Valid values are notlink. Valid values match /./. at /etc/puppetlabs/code/environments/production/modules/icingaweb2/manifests/module.pp:91
```
## Expected Behavior

Either the code should require the module_dir parameter to be set or a more sane default should be chosen.

## Current Behavior

The code doesn't compile

## Possible Solutions

* Make it a required parameter. Or
* Provide a sane default

Defining a sane default is difficult. Should the 'sane' default be ${::icingaweb2::params::conf_dir}/${title} or ${::icingaweb2::params::module_path}/${title}?  The default can be set based on the install_method:
* none: ${::icingaweb2::params::module_path}/${title}
* git: ${::icingaweb2::params::conf_dir}/${title}

## Context

When enabling one of the modules provided by the package the error occurred.  I was assuming the define would be clever enough to pick the correct path.

**Comment by bobapple** [comment]
My intention was to make `module_dir` required when using `icingaweb2::module`, however the implementation is wrong. I use `validate_string` instead of `validate_absolute_path`, which won't throw an error with Puppet 3.

I think the only sane default value would be `${::icingaweb2::params::module_path}/${title}`, because `${::icingaweb2::params::conf_dir}` is meant to hold module configuration files, not the source of a module.

If someone doesn't want to use `${::icingaweb2::params::module_path}/${title}` as location for the module source, which is totally fine and possible, he will have to update the `module_path` in `config.ini` as well.

I suggest we set `${::icingaweb2::params::module_path}/${title}` as default for `module_dir`.

**Comment by rgevaert** [comment]
I agree. Thanks!
