### ISSUE TITLE
Question: Puppet 3 support

### ISSUE THREAD

**Issue by baurmatt** [Icinga/puppet-icingaweb2#164]
I would like to offer a PR which moves all code to Puppet 4 data types/style as I've already done for puppet-icinga2 (https://github.com/Icinga/puppet-icinga2/pull/350). But lately i found this statement by @bobapple https://github.com/Icinga/puppet-icingaweb2/pull/156#issuecomment-324318222 which make me wonder why you're still want to keep the module compatible with Puppet 3. How long are you planning to support Puppet 3? Is there a plan for Puppet 4 only support?

**Comment by bobapple** [comment]
I'm currently thinking of dropping the Puppet 3 support for both modules, icinga2 and icingaweb2. It would probably make sense to make a puppet-icinga2 2.0 with all the changes that break compatibility and drop the Puppet 3 support as well. If we decide to do this with the icinga2 module, it would make sense to change development in the icingaweb2 module as well, since 2.0 is not released yet.

Give me some time, I will let you know how we will proceed. Thank you for your effort so far!

**Comment by bobapple** [comment]
Please refer to this puppet-icinga2 issue regarding this topic: https://github.com/Icinga/puppet-icinga2/pull/362

**Comment by lbetz** [comment]
We should keep this dead branch for compatibly and for the people those who wanna use it.

**Comment by bobapple** [comment]
The old releases with Puppet 3 support will still be available. I think a tagged version is much better usable for someone who has Puppet 3 then cloning a special branch of a git repo.

**Comment by lbetz** [comment]
ok, right if you need it can branch the tag of course.

**Comment by bobapple** [comment]
We're dropping Puppet 3 support for milestone 2.0 of this module. We will do the same for puppet-icinga2 as well for the next major release (also milestone 2.0).

Everything related to Puppet 3 may be removed and replaced here. I'll start working on this as soon as time allows, PRs are welcome as always.

**Comment by baurmatt** [comment]
I would do the data type migration but could you please review/merge #162 first as it would probably best to have functional tests :) Thanks! :)

**Comment by bobapple** [comment]
Thank you @baurmatt 👍
