### ISSUE TITLE
[dev.icinga.com #12142] Why does initialize.pp require /root/.my.cnf on RedHat/CentOS, not Debian/Ubuntu?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/puppet-icingaweb2#61]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12142

**Created by westbywest on 2016-07-12 17:46:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-12 17:46:51 +00:00 (in Redmine)_

---

I noticed these recent commits altering initialize.pp to support a remote MySQL host under Debian/Ubuntu:
https://github.com/Icinga/puppet-icingaweb2/commit/475e0c9cfc59c50d0aca4ba0536f93c8fba29cb5
https://github.com/Icinga/puppet-icingaweb2/commit/41c46bdf02d4022887d34f32ed91da690240b244

However, the clause for RedHat/CentOS still references the file /root/.my.cnf, meaning a remote MySQL host would only be possible by inserting references to it into /root/.my.cnf prior to invoking icingaweb2 module.

Is there a reason for this difference between RedHat and Debian?

**Comment by visibilityspots** [comment]
The reason of the initial RedHat/CentOS only implementation is because I only tested it on such an operating systems. It seems that @ngoduykhanh has added the Debian/Ubuntu OS too in https://github.com/Icinga/puppet-icingaweb2/commit/41c46bdf02d4022887d34f32ed91da690240b244 so I guess he tested it on both operating systems?

**Comment by bobapple** [comment]
This is most likely not relevant anymore with the current development.
